// Validate the v2 delivery-gate judge against the referent ladder's blind
// verdicts — the first ground truth this project has that contains AGREED
// FUNDABLE documents, so a judge can finally be scored in both directions.
//
//   OPENROUTER_API_KEY=... npx --yes deno@2.9.5 run \
//     --allow-net=openrouter.ai --allow-read --allow-env \
//     tests/delivery-gate/validate_judge_ladder.ts
//
//   --models=z-ai/glm-5.3-flash[,google/gemini-3.7-flash]  candidates, in order
//   --budget-usd=3.00                                      HARD cap on spend
//   --dry-run                                              plan only, no calls
//
// GROUND TRUTH. The 14 blind verdict files (tests/ladder/verdicts/ x10,
// tests/ladder/verdicts2/ x4) each record per-document "fundable as submitted:
// yes/no" for 4 documents. Doc-n -> arm decoding comes from each file's own
// derived-blinding header comment; the four files that predate the header carry
// the decode recorded in reports/phase1-verdicts.md (landed 2026-08-27 rows),
// every one of which bytematch.py pins to the packets' actual bytes. That
// yields 56 document-level judgements over the 22 documents. A document whose
// critics disagree is DISPUTED and excluded from the headline rate; the count
// is reported. Each per-critic judgement on an undisputed document is one
// datum.
//
// FAMILY RULE, in the harness too: arms A and C were generated by
// google/gemini-3.7-flash. When the candidate under test is in the google
// family, those documents are excluded from its rate — the generator never
// grades its own work, and a validation number earned by breaking that rule
// would be unusable for the wiring decision it exists to make.
//
// SPEND. Every call carries usage.include=true and its cost is read from the
// provider's own accounting. The budget is a HARD stop checked BEFORE each
// call; what remains unjudged is recorded as unjudged, never guessed. A call
// that dies is retried once (generation id kept where the reply carried one),
// then recorded MISSING.

import {
  JUDGE_PRIMARY, JUDGE_FALLBACK, JUDGE_SEED, JUDGE_TEMPERATURE, JUDGE_EFFORT,
  JUDGE_SLOTS, applyBar, buildJudgeRequest, judgeView, parseJudgeReply,
  gateScore, classifyProviderError, modelFamily,
} from "../../supabase/functions/worker/delivery_gate.ts";
import type { GateInput, CriticRequest } from "../../supabase/functions/worker/delivery_gate.ts";

const ROOT = new URL("../..", import.meta.url).pathname;
const LADDER = `${ROOT}tests/ladder`;

function arg(name: string, fallback: string): string {
  const hit = Deno.args.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
}
const DRY = Deno.args.includes("--dry-run");
const MODELS = arg("models", JUDGE_PRIMARY).split(",").map((s) => s.trim()).filter(Boolean);
const BUDGET_USD = Number(arg("budget-usd", "3.00"));

// ---------------------------------------------------------------- ground truth
type Verdict = "fundable" | "not_fundable";

// The decode for the four verdict files written before the runner stamped the
// derived-blinding header. Values are the "landed 2026-08-27" orders recorded
// in reports/phase1-verdicts.md and confirmed by bytematch fingerprints.
const LEGACY_DECODE: Record<string, string> = {
  "verdicts/critic-n06-critic_b.md": "DCAB",
  "verdicts/critic-n12-critic_b.md": "BDAC",
  "verdicts/critic-n06thin-critic_a.md": "BDCA",
  "verdicts/critic-n06thin-critic_b.md": "DCAB",
};

const VERDICT_FILES: Array<{ rel: string; rung: string; critic: string }> = [];
for (const dir of ["verdicts", "verdicts2"]) {
  for (const e of [...Deno.readDirSync(`${LADDER}/${dir}`)].sort((a, b) => a.name.localeCompare(b.name))) {
    const m = e.name.match(/^critic-(.+)-(critic_[ab])\.md$/);
    if (m) VERDICT_FILES.push({ rel: `${dir}/${e.name}`, rung: m[1], critic: m[2] });
  }
}

function decodeFor(rel: string, md: string): Record<string, string> {
  const header = md.match(/blinding DERIVED from packet bytes:\s*(\{[^}]+\})/);
  if (header) return JSON.parse(header[1]) as Record<string, string>;
  const legacy = LEGACY_DECODE[rel];
  if (!legacy) throw new Error(`${rel}: no blinding header and no recorded legacy decode — refusing to guess`);
  const out: Record<string, string> = {};
  legacy.split("").forEach((arm, i) => { out[`Doc ${i + 1}`] = arm; });
  return out;
}

// Per-doc "fundable as submitted" lines, tolerant of every format the two
// critics actually used ("- **Fundable as submitted:** No.", "- fundable as
// submitted: y", "**Y** (barely)", "Yes, narrowly"), and strict about count:
// a file that does not yield exactly four verdicts stops the run.
function verdictsByDoc(md: string): Record<string, Verdict> {
  const out: Record<string, Verdict> = {};
  let current: string | null = null;
  for (const raw of md.split("\n")) {
    const line = raw.replace(/\*/g, "").trim();
    const head = line.match(/^(?:#{0,4}\s*)?(?:\d+\.\s*)?Doc\s+(\d)\s*$/i);
    if (head) { current = `Doc ${head[1]}`; continue; }
    const v = line.match(/^[-\s]*fundable as submitted\s*:?\s*(yes|no|y|n)\b/i);
    if (v && current && !(current in out)) {
      out[current] = /^y/i.test(v[1]) ? "fundable" : "not_fundable";
    }
  }
  return out;
}

interface Datum { rung: string; arm: string; critic: string; file: string; verdict: Verdict }
const data: Datum[] = [];
for (const f of VERDICT_FILES) {
  const md = Deno.readTextFileSync(`${LADDER}/${f.rel}`);
  const decode = decodeFor(f.rel, md);
  const per = verdictsByDoc(md);
  const docs = Object.keys(per);
  if (docs.length !== 4) {
    throw new Error(`${f.rel}: expected 4 'fundable as submitted' verdicts, parsed ${docs.length} (${docs.join(", ")}) — a parser that quietly drops verdicts biases the rate`);
  }
  for (const [doc, v] of Object.entries(per)) {
    const armCode = decode[doc];
    if (!armCode) throw new Error(`${f.rel}: no decode for ${doc}`);
    data.push({ rung: f.rung, arm: armCode, critic: f.critic, file: f.rel, verdict: v });
  }
}

interface DocTruth { rung: string; arm: string; generator: string; judgements: Datum[]; consensus: Verdict | "disputed" }
const byDoc = new Map<string, DocTruth>();
for (const d of data) {
  const key = `${d.rung}-${d.arm}`;
  if (!byDoc.has(key)) {
    const meta = JSON.parse(Deno.readTextFileSync(`${LADDER}/fixture/meta-${d.rung}-${d.arm}.json`)) as { model?: string };
    byDoc.set(key, { rung: d.rung, arm: d.arm, generator: String(meta.model ?? ""), judgements: [], consensus: "disputed" });
  }
  byDoc.get(key)!.judgements.push(d);
}
for (const t of byDoc.values()) {
  const vs = new Set(t.judgements.map((j) => j.verdict));
  t.consensus = vs.size === 1 ? t.judgements[0].verdict : "disputed";
}
const docs = [...byDoc.values()].sort((a, b) => `${a.rung}-${a.arm}`.localeCompare(`${b.rung}-${b.arm}`));
const disputed = docs.filter((d) => d.consensus === "disputed");

// ---------------------------------------------------------------- the input
const fixture = JSON.parse(Deno.readTextFileSync(`${LADDER}/fixture/grant.json`)) as {
  grant: { funder: string; programme: string; full_guidelines_text: string };
};
const org = JSON.parse(Deno.readTextFileSync(`${LADDER}/fixture/org.json`)) as {
  legal_name: string; website: string; town_or_city: string; country: string;
};
const GRANT_TEXT = `${fixture.grant.funder} — ${fixture.grant.programme}\n\n${fixture.grant.full_guidelines_text}`;

function gateInputFor(d: DocTruth): GateInput {
  return {
    narrative: Deno.readTextFileSync(`${LADDER}/documents/out-${d.rung}-${d.arm}.md`),
    applicantName: org.legal_name,
    applicantLine: `${org.legal_name} · ${org.town_or_city}, ${org.country} · ${org.website}`,
    grantText: GRANT_TEXT,
    fmt: { maxWords: null }, // the judge is told not to count; the word limit is checked deterministically elsewhere
    evidence: [],            // the judge never sees the ledger; preflight is not what is being validated
    generatorModel: d.generator,
  };
}

// ---------------------------------------------------------------- the call
// The key comes from the environment, or from an env-format file passed as
// --key-file (the operator's stack/.env). It is used in one header and is
// never printed, logged, or written anywhere.
function readKey(): string {
  const env = Deno.env.get("OPENROUTER_API_KEY");
  if (env) return env;
  const file = arg("key-file", "");
  if (!file) return "";
  try {
    const m = Deno.readTextFileSync(file).match(/^OPENROUTER_API_KEY=(.+)$/m);
    return m ? m[1].trim().replace(/^["']|["']$/g, "") : "";
  } catch { return ""; }
}
const KEY = readKey();
let spentUsd = 0;
let unmeasuredCalls = 0;

class BudgetStop extends Error {}

async function call(req: CriticRequest): Promise<{ text: string; usd: number | null; id: string | null }> {
  // HARD budget, checked BEFORE the call. A conservative reserve of the worst
  // call seen so far (or $0.05 before any call has priced) keeps the last call
  // from overshooting the cap.
  const reserve = Math.max(0.05, worstCallUsd);
  if (spentUsd + reserve > BUDGET_USD) {
    throw new BudgetStop(`spent $${spentUsd.toFixed(4)}, reserve $${reserve.toFixed(4)}, budget $${BUDGET_USD.toFixed(2)}`);
  }
  const r = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${KEY}`, "HTTP-Referer": "https://ktebli.com", "X-Title": "Ktebli judge validation (ladder)" },
    body: JSON.stringify({
      model: req.model,
      max_tokens: req.maxTokens,
      temperature: req.temperature ?? JUDGE_TEMPERATURE,
      seed: req.seed ?? JUDGE_SEED,
      reasoning: { effort: req.effort },
      response_format: req.responseFormat,
      usage: { include: true },
      messages: [{ role: "user", content: req.prompt }],
    }),
  });
  const text = await r.text();
  if (!r.ok) {
    const err = `HTTP ${r.status} ${text.slice(0, 300)}`;
    if (classifyProviderError(err) === "cap") throw new BudgetStop(`provider cap: ${err}`);
    throw new Error(err);
  }
  const j = JSON.parse(text);
  const usd = typeof j.usage?.cost === "number" ? j.usage.cost : null;
  if (usd === null) unmeasuredCalls++;
  else { spentUsd += usd; worstCallUsd = Math.max(worstCallUsd, usd); }
  return { text: j.choices?.[0]?.message?.content ?? "", usd, id: typeof j.id === "string" ? j.id : null };
}
let worstCallUsd = 0;

// ---------------------------------------------------------------- one judgement
interface Row {
  model: string; doc: string; truth: Verdict | "disputed";
  ownFamily: boolean;                       // candidate family generated this doc
  gate: Verdict | "MISSING"; score: number | null;
  usd: number | null; generation_id: string | null; error: string | null;
}

async function judgeOne(d: DocTruth, model: string): Promise<Row> {
  const input = gateInputFor(d);
  const req = buildJudgeRequest(judgeView(input), { ...JUDGE_SLOTS[0], model });
  const row: Row = {
    model, doc: `${d.rung}-${d.arm}`, truth: d.consensus,
    ownFamily: modelFamily(model) === modelFamily(d.generator),
    gate: "MISSING", score: null, usd: null, generation_id: null, error: null,
  };
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const reply = await call(req);
      row.usd = (row.usd ?? 0) + (reply.usd ?? 0);
      row.generation_id = reply.id ?? row.generation_id;
      const parsed = parseJudgeReply(reply.text);
      if (!parsed.ok) { row.error = parsed.reason; continue; }
      const bar = applyBar(parsed.judgement);
      row.gate = bar.clears ? "fundable" : "not_fundable";
      row.score = gateScore(parsed.judgement);
      row.error = null;
      return row;
    } catch (e) {
      if (e instanceof BudgetStop) throw e;
      row.error = String(e).slice(0, 240);
    }
  }
  return row; // MISSING after one retry, generation id kept where one landed
}

// ---------------------------------------------------------------- reporting
interface Rate { n: number; agree: number; rate: number; baseline: number; falsePass: number; falseHold: number; missing: number; excluded: number }

function rateFor(rows: Row[], model: string): Rate {
  const fam = modelFamily(model);
  const excluded = rows.filter((r) => r.model === model && r.ownFamily).length;
  // Datum-level: each per-critic judgement on an undisputed, family-legal
  // document is one datum, compared against the judge's per-document verdict.
  let n = 0, agree = 0, hold = 0, falsePass = 0, falseHold = 0, missing = 0;
  for (const d of docs) {
    if (d.consensus === "disputed") continue;
    if (modelFamily(d.generator) === fam) continue;
    const r = rows.find((x) => x.model === model && x.doc === `${d.rung}-${d.arm}`);
    if (!r) continue;
    for (const j of d.judgements) {
      if (r.gate === "MISSING") { missing++; continue; }
      n++;
      if (j.verdict === "not_fundable") hold++;
      if (r.gate === j.verdict) agree++;
      else if (r.gate === "fundable") falsePass++;
      else falseHold++;
    }
  }
  return { n, agree, rate: n ? agree / n : 0, baseline: n ? hold / n : 0, falsePass, falseHold, missing, excluded };
}

// ---------------------------------------------------------------- main
console.log(`ground truth: ${docs.length} documents, ${data.length} critic judgements, ${disputed.length} DISPUTED (excluded from the rate):`);
for (const d of docs) {
  console.log(`  ${(d.rung + "-" + d.arm).padEnd(12)} gen=${d.generator.padEnd(28)} [${d.judgements.map((j) => `${j.critic.slice(-1)}:${j.verdict === "fundable" ? "Y" : "N"}`).join(" ")}] -> ${d.consensus}`);
}
const decided = docs.filter((d) => d.consensus !== "disputed");
const fundableDocs = decided.filter((d) => d.consensus === "fundable").length;
console.log(`corpus balance (documents): ${fundableDocs} fundable, ${decided.length - fundableDocs} not fundable, ${disputed.length} disputed`);
console.log(`candidates: ${MODELS.join(", ")} · fixed: temp ${JUDGE_TEMPERATURE}, seed ${JUDGE_SEED}, effort ${JUDGE_EFFORT}, structured outputs, NEUTRAL v2 instrument`);
console.log(`budget: $${BUDGET_USD.toFixed(2)} HARD\n`);

if (DRY) {
  const req = buildJudgeRequest(judgeView(gateInputFor(docs[0])), { ...JUDGE_SLOTS[0], model: MODELS[0] });
  console.log(`--dry-run: up to ${docs.length * MODELS.length} calls. First request: model=${req.model} effort=${req.effort} temp=${req.temperature} seed=${req.seed} prompt=${req.prompt.length} chars schema=${req.responseFormat?.json_schema.name}`);
  Deno.exit(0);
}
if (!KEY) {
  console.error("OPENROUTER_API_KEY is not set. Refusing to report an agreement rate that was never measured.");
  Deno.exit(1);
}

const rows: Row[] = [];
let stopped: string | null = null;
outer:
for (const model of MODELS) {
  for (const d of docs) {
    if (modelFamily(model) === modelFamily(d.generator)) {
      console.error(`  ${model} ${d.rung}-${d.arm}: SKIPPED (generator's own family; never judged, never billed)`);
      continue;
    }
    try {
      const r = await judgeOne(d, model);
      rows.push(r);
      console.error(`  ${model} ${d.rung}-${d.arm}: ${r.gate}${r.score !== null ? ` (score ${r.score})` : ""}${r.error ? ` [${r.error.slice(0, 80)}]` : ""} $${(r.usd ?? 0).toFixed(4)}`);
    } catch (e) {
      if (e instanceof BudgetStop) { stopped = String(e.message); break outer; }
      throw e;
    }
  }
}

console.log(`\nmodel                              n(data)  agree  rate    always-hold  false-pass  false-hold  missing  own-family-excluded`);
for (const model of MODELS) {
  if (!rows.some((r) => r.model === model)) continue;
  const s = rateFor(rows, model);
  console.log(
    `${model.padEnd(34)} ${String(s.n).padEnd(8)} ${String(s.agree).padEnd(6)} ${(s.rate * 100).toFixed(1).padStart(5)}%  ` +
    `${(s.baseline * 100).toFixed(1).padStart(10)}%  ${String(s.falsePass).padStart(10)}  ${String(s.falseHold).padStart(10)}  ` +
    `${String(s.missing).padStart(7)}  ${String(s.excluded).padStart(3)} doc(s)`,
  );
  if (s.n && s.rate <= s.baseline) console.log(`   ^ NO SIGNAL: does not beat refusing everything.`);
}
console.log(`\nDISPUTED documents excluded from every rate: ${disputed.length} (${disputed.map((d) => `${d.rung}-${d.arm}`).join(", ")})`);
console.log(`total measured spend: $${spentUsd.toFixed(4)} over ${rows.length} judged documents` +
  (unmeasuredCalls ? `; ${unmeasuredCalls} call(s) carried no cost accounting` : ""));
if (stopped) console.log(`STOPPED BEFORE THE BUDGET: ${stopped}. Documents not judged are reported MISSING/absent, never guessed.`);

console.log(`\nDecision rule (phase brief): wire the primary if agreement >= 80%; else try the fallback as primary;` +
  ` if both miss, wire the better one hold-biased and flag LOW-AGREEMENT.`);
