const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync('index.html', 'utf8');
class Element {
  constructor() { this.children=[]; this.style={}; this.dataset={}; this.value=''; this.events={}; this.classes=new Set(); this.classList={add:(name)=>this.classes.add(name),remove:(name)=>this.classes.delete(name),contains:(name)=>this.classes.has(name)}; this.offsetWidth=0; }
  appendChild(x) { this.children.push(x); return x; }
  append(...items) { this.children.push(...items); }
  replaceChildren() { this.children=[]; }
  addEventListener(k,v) { this.events[k]=v; }
  dispatchEvent(e) { if(this.id==='w-grant')input=this.value; if(this.events[e.type])this.events[e.type].call(this,e); }
  focus() { this.focused=true; }
  setAttribute(k,v) { this[k]=v; }
}
const elements = new Map();
const document = {createElement:()=>new Element(),querySelector:()=>new Element(),getElementById:(id)=>{if(!elements.has(id)){const e=new Element();e.id=id;elements.set(id,e);}return elements.get(id);}};
let input='https://example.org/tender', response, requests=[], timers=[], delays=[];
const ctx = {document,URL,console, catalogueHandoffPending:false, catalogueHandoffEpoch:0, Event:class {constructor(type){this.type=type;}}, FN:'https://backend.example', wiz:{step:0,val:()=>input},cb:(id)=>!!document.getElementById(id).checked,updateDeadlineField(){},clearTimeout(){},setTimeout(fn,delay){timers.push(fn);delays.push(delay);return timers.length;},fetch:async(url,options)=>{requests.push(JSON.parse(options.body));return {json:async()=>response};}};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function proposalCurrency()'),html.indexOf("document.getElementById('w-currency').addEventListener('change'")),ctx);
vm.runInContext(html.slice(html.indexOf('var lastAnalyzed ='),html.indexOf('function updateDeadlineField()')),ctx);
const flush=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 function content(node){return [node.textContent||'',...(node.children||[]).map(content)].join(' ');}
 const reading=ctx.opportunityProgress({status:'processing',progress:{phase:'reading',sources_completed:2,sources_total:9,pages_completed:100,pages_total:1155,background:true}});
 assert.match(content(reading),/2 of 9 sources read/);assert.match(content(reading),/100 of 1155 pages read/);
 assert.match(content(reading),/Continue with your organisation’s details/);assert.equal(reading['aria-live'],'polite');
 assert.equal(reading.children[0].children[1]['aria-current'],'step');
 const verifying=ctx.opportunityProgress({status:'processing',progress:{phase:'verifying',pages_completed:1155,pages_total:1155}});
 assert.match(content(verifying),/reconciling any differences/);assert.match(content(verifying),/Continue with your organisation’s details/);
 assert.equal(verifying.children[0].children[3].className,undefined);
 const invalid=ctx.opportunityProgress({status:'processing',progress:{phase:'ready',pages_completed:8,pages_total:3,sources_completed:'<script>',sources_total:9}});
 assert.doesNotMatch(content(invalid),/8 of 3|<script>|Source review complete/);
 const unknown=ctx.opportunityProgress({status:'processing',progress:{phase:'reading',pages_completed:8,pages_total:null}});
 assert.match(content(unknown),/8 pages read — finding the full total/);
 ctx.showOpportunityResult({status:'ready',requirements_count:1000,requirements_previewed:true,requirements:[{text:'First exact requirement',source_url:'https://issuer.gov'}]});
 assert.match(content(document.getElementById('gpreview')),/retained 1000 requirements\. Showing 1 here/);
 assert.match(content(document.getElementById('gpreview')),/Requirements preview/);
 ctx.showOpportunityResult({status:'ready',title:'Community learning programme',issuer:'Ministry of Education',looking_for:'Train community tutors and provide learning materials.',deadline:'2026-11-20',deadline_needs_verification:true,deadline_warning:'Two submission dates appear in the source. Please verify with the issuer.',deadline_sources:[{date:'2026-11-20',source_url:'https://issuer.gov/call'}],amount:'50,000',currency:'USD',quick_preview:{status:'preview',display_title:'Unreviewed page title',deadline_excerpt:'A different date',funding_excerpt:'A different amount',deadline_warning:'Quick preview warning'}});
 const readyCard=document.getElementById('gpreview'),readyText=content(readyCard);
 assert.match(readyText,/Community learning programme.*Source review complete/);
 assert.match(readyText,/Deadline 2026-11-20.*Funding USD 50,000.*Scope Train community tutors and provide learning materials/);
 assert.match(readyText,/Two submission dates appear in the source/);
 assert.match(readyText,/2026-11-20 — view source/);
 assert.doesNotMatch(readyText,/Unreviewed page title|A different date|A different amount|Quick preview warning|Requirements ready|Find documents|cached source review|Quick page preview/);
 ctx.showOpportunityResult({status:'processing',awaiting_payment:true,quick_preview:{status:'unavailable',expected:'Full reading after payment'}});
 assert.match(content(document.getElementById('gpreview')),/Link saved.*after payment/);
 assert.match(content(document.getElementById('gpreview')),/Paste full page text/);
 assert.equal((content(document.getElementById('gpreview')).match(/Link saved/g)||[]).length,1);
 assert.equal(document.getElementById('gpreview')['aria-busy'],'false');
 assert.doesNotMatch(content(document.getElementById('gpreview')),/Not found on this page|Not stated on this page/);
 ctx.showOpportunityResult({status:'blocked',message:'The illustrative source could not be read.',quick_preview:{status:'preview',display_title:'Illustrative source unavailable',failure_reason:'verification_required'}});
 assert.match(content(document.getElementById('gpreview')),/The illustrative source could not be read/);
 assert.doesNotMatch(content(document.getElementById('gpreview')),/undefined/,'partial source preview fields stay omitted instead of rendering undefined');
 ctx.showOpportunityResult({status:'processing',awaiting_payment:true,quick_preview:{status:'preview',expected:'Full reading after payment'}});
 assert.match(content(document.getElementById('gpreview')),/Deadline Not confirmed from this page/);
 ctx.showOpportunityResult({status:'processing',awaiting_payment:true,quick_preview:{status:'preview',funding_excerpt:null,currency:'USD'}});
 assert.match(content(document.getElementById('gpreview')),/Funding Will be extracted from documents/);
 assert.doesNotMatch(content(document.getElementById('gpreview')),/Funding currency/);
 ctx.showOpportunityResult({status:'processing',awaiting_payment:true,quick_preview:{status:'preview',funding_excerpt:'Maximum grant USD 1,000,000',currency:'USD'}});
 assert.match(content(document.getElementById('gpreview')),/Funding Maximum grant USD 1,000,000/);
 assert.match(content(document.getElementById('gpreview')),/Funding currency USD/);
 ctx.showOpportunityResult({status:'processing',awaiting_payment:true,quick_preview:{status:'preview',deadline_excerpt:'Extended Deadline for Submission of Bids 26 Oct 2026 12:00 o’clock noon Beirut local time'}});
 const deadlineCard=document.getElementById('gpreview');
 const compactDeadline=deadlineCard.children.find(n=>n.className==='gp-r');
 assert.equal(compactDeadline.children[0].textContent,'Deadline');
 assert.equal(compactDeadline.children[1].textContent,'26 Oct 2026 12:00 o’clock noon Beirut local time');
 const sourceDetails=deadlineCard.children.find(n=>n.className==='preview-more');
 assert.match(content(sourceDetails),/Extended Deadline for Submission of Bids 26 Oct 2026/);
 assert.equal(ctx.previewDeadlineDate('Deadline 22 Oct 2026 12:00 o’clock noon Beirut local time'),'2026-10-22');
 assert.equal(ctx.previewDeadlineDate('Deadline 22 Oct 2026 or 24 Oct 2026'),'');
 assert.equal(ctx.previewFunding('Grant amount up to USD 1,000,000','USD'),'Grant amount up to USD 1,000,000');
 assert.equal(ctx.previewFunding('Grant amount 50,000 euros','EUR'),'Grant amount 50,000 euros');
 assert.equal(ctx.previewFunding('Grant amount 25,000 dollars',''),'');
 assert.equal(ctx.previewFunding('Grant amount 25,000 dollars','CAD'),'Grant amount 25,000 dollars');
 assert.equal(ctx.previewFunding('grant amount usd 50,000','USD'),'grant amount usd 50,000');
 assert.equal(ctx.previewFunding('Grant amount $25,000','AED'),'');
 assert.equal(ctx.previewFunding('Tender dossier fee USD 1,000','USD'),'');
 assert.equal(ctx.previewFunding('Funding up to 1,000,000','CAD'),'Funding up to 1,000,000 · CAD');
 response={status:'processing',extraction_id:'id-1',extraction_token:'secret'};
 ctx.analyzeGrant(); assert.equal(document.getElementById('gpreview')['aria-busy'],'true');assert.match(content(document.getElementById('gpreview')),/Finding opportunity details/); await flush();
 assert.equal(ctx.analysisOk,false);assert.equal(document.getElementById('wiz-next').disabled,true);
 assert.equal(timers.length,1);
 assert.equal(delays[0],3000);
 // A pending source permits intake and checkout without public paid reading.
 response={status:'processing',awaiting_payment:true,extraction_id:'id-1',extraction_token:'secret',progress:{phase:'awaiting_payment',background:false}};
 ctx.analyzeGrant(true,true);await flush();
 assert.equal(ctx.analysisOk,true);assert.equal(ctx.analysisReady,false);assert.equal(ctx.canContinueIntake(),true);assert.equal(document.getElementById('wiz-next').disabled,false);
 assert.match(content(document.getElementById('gpreview')),/document reading starts after payment/);
 ctx.opportunityExtractionToken='';assert.equal(ctx.canContinueIntake(),false);ctx.opportunityExtractionToken='secret';

 response={status:'ready',extraction_id:'id-1',extraction_token:'secret',currency:'USD',proposal_type:'government_tender',title:'<script>no</script>',documents:[{url:'javascript:alert(1)',title:'bad',status:'read'}],requirements:[{text:'Must submit a bond',source_url:'https://example.org/spec.pdf'}]};
 timers.shift()(); await flush();
 assert.deepEqual(requests[2],{extraction_id:'id-1',extraction_token:'secret'});
 assert.equal(ctx.analysisOk,true);assert.equal(document.getElementById('wiz-next').disabled,false);
 assert.equal(document.getElementById('w-currency').value,'');
 assert.equal(document.getElementById('proposal-currency-fields').hidden,true);
 assert.equal(ctx.sourceLink('javascript:alert(1)','unsafe').href,undefined);
 assert.equal(ctx.sourceLink('https://example.org/spec.pdf','safe').rel,'noopener noreferrer');
 response={status:'ready',extraction_id:'id-1',extraction_token:'secret',deadline:'2026-10-08',deadline_needs_verification:true,deadline_warning:'We found 2026-10-08 and 2026-10-10. Please double-check.',deadline_sources:[{date:'2026-10-08',source_url:'https://issuer.example/notice'}]};
 ctx.analyzeGrant(true,true); await flush();
 assert.equal(ctx.analysisOk,true); assert.equal(document.getElementById('wiz-next').disabled,false);
 assert.equal(ctx.canContinueIntake(),true, 'source review is ready; wizard validation must still require deadline confirmation');
 document.getElementById('w-deadline-confirm').checked=true;
 const warning=document.getElementById('gpreview').children.find(n=>n.className==='deadline-warning');
 assert.equal(warning.role,'alert'); assert.match(warning.children[1].textContent,/2026-10-08 and 2026-10-10/);
 assert.equal(ctx.deadlineNeedsVerification,true);assert.equal(ctx.deadlineRequiresManual,false);
 response={status:'ready',extraction_id:'id-1',extraction_token:'secret',deadline:null,deadline_requires_manual_entry:true,deadline_needs_verification:true};
 ctx.analyzeGrant(true,true);await flush();
 assert.equal(ctx.analysisOk,true);assert.equal(ctx.deadlineRequiresManual,true);assert.equal(ctx.analyzedDeadline,'');
 vm.runInContext(html.slice(html.indexOf('function updateDeadlineField()'),html.indexOf("document.getElementById('w-deadline-confirm').addEventListener('change'")),ctx);
 ctx.updateDeadlineField();assert.equal(document.getElementById('deadline-manual').style.display,'block');
 assert.equal(document.getElementById('deadline-confirmation').style.display,'block');
 assert.match(document.getElementById('deadline-confirm-label').textContent,/supplied by me, not verified/);
 assert.equal(ctx.validDeadline('2027-02-30'),false);assert.equal(ctx.validDeadline('2028-02-29'),true);
 // Accepted Jev selections fill supported fields, with visible advisory labels.
 response={status:'processing',awaiting_payment:true,extraction_id:'id-1',extraction_token:'secret',quick_preview:{status:'preview',suggestion_method:'jev_source_selection',display_title:'Construction of the coastal road',raw_title:'CDR Notice — Construction of the coastal road',proposal_type:'government_tender',subject:'construction',currency:null,deadline_excerpt:'Extended Deadline for Submission of Bids 26 Oct 2026 12:00 noon Beirut time'}};
 ctx.analyzeGrant(true);await flush();
 assert.equal(document.getElementById('w-proposal-type').value,'government_tender');
 assert.equal(document.getElementById('w-subject').value,'construction');
 assert.equal(document.getElementById('w-currency').value,'');
 assert.equal(document.getElementById('w-proposal-type-detected').hidden,false);
 assert.equal(document.getElementById('w-currency-detected').hidden,true);
 assert.match(document.getElementById('opportunity-filled').textContent,/2 details filled.*proposal type, field/);
 assert.equal(ctx.opportunityDetails.display_title,'Construction of the coastal road');
 assert.equal(ctx.analyzedDeadline,''); // the page excerpt is advisory, never a verified date
 assert.equal(document.getElementById('w-deadline').value,'2026-10-26');
 assert.equal(document.getElementById('w-deadline').dataset.autoDetected,'true');
 assert.equal(ctx.deadlineForSubmission(),'');
 ctx.deadlineRequiresManual=true;document.getElementById('w-deadline-confirm').checked=true;
 assert.equal(ctx.deadlineForSubmission(),'2026-10-26');
 document.getElementById('w-deadline-confirm').checked=false;
 assert.equal(ctx.deadlineForSubmission(),'');ctx.deadlineRequiresManual=false;
 // Competing PPA submission dates stay visible; earliest is advisory and needs confirmation.
 response.quick_preview.deadline_excerpt='Deadline for submission of offers : 2026-10-07 12:00:00';
 response.quick_preview.deadline_needs_verification=true;
 response.quick_preview.deadline_warning='This page lists different submission dates. Plan for the earliest and verify with the issuer.';
 response.quick_preview.deadline_candidates=['Deadline for submission of offers : 2026-10-07 12:00:00','Deadline for submission of offers 2026-10-08 12:00:00'];
 ctx.analyzeGrant(true);await flush();
 assert.equal(document.getElementById('w-deadline').value,'2026-10-07');assert.equal(ctx.analyzedDeadline,'');
 assert.equal(ctx.deadlineNeedsVerification,true);
 assert.equal(ctx.deadlineForSubmission(),'');
 const conflictCard=document.getElementById('gpreview');
 assert.match(content(conflictCard),/2026-10-07 12:00:00.*2026-10-08 12:00:00/);
 const conflictWarning=conflictCard.children.find(n=>n.className==='deadline-warning');
 assert.equal(conflictWarning.role,'alert');assert.match(conflictWarning.textContent,/different submission dates/);
 ctx.updateDeadlineField();assert.equal(document.getElementById('deadline-confirmation').style.display,'block');
 assert.equal(ctx.compactPreviewDeadline(response.quick_preview.deadline_excerpt),'2026-10-07 12:00:00');
 response.quick_preview.deadline_excerpt='Extended Deadline for Submission of Bids 26 Oct 2026 12:00 noon Beirut time';
 delete response.quick_preview.deadline_needs_verification;delete response.quick_preview.deadline_warning;delete response.quick_preview.deadline_candidates;
 ctx.analyzeGrant(true);await flush();assert.equal(ctx.deadlineNeedsVerification,false);
 const type=document.getElementById('w-proposal-type');type.value='business';type.dataset.userSelected='true';delete type.dataset.detected;
 response.quick_preview.currency='AED';response.quick_preview.funding_excerpt='Grant amount AED 25,000';ctx.analyzeGrant(true);await flush();
 assert.equal(type.value,'business');assert.equal(document.getElementById('w-proposal-type-detected').hidden,true);
 assert.equal(document.getElementById('w-currency').value,'other');assert.equal(document.getElementById('w-currency-other').value,'AED');
 assert.equal(document.getElementById('proposal-currency-fields').hidden,false);
 assert.equal(document.getElementById('w-currency-detected').hidden,false);
 const deadline=document.getElementById('w-deadline');deadline.value='2026-10-26';deadline.dataset.autoDetected='true';ctx.deadlinePreviewPrefill=true;
 assert.equal(ctx.deadlineForSubmission(),'');
 deadline.dataset.userSelected='true';delete deadline.dataset.autoDetected;
 assert.equal(ctx.deadlineForSubmission(),'2026-10-26');
 ctx.deadlineRequiresManual=false;ctx.analyzedDeadline='2026-10-27';
 assert.equal(ctx.deadlineForSubmission(),'2026-10-27');
 await flush();ctx.analyzeGrant(true);await flush();
 assert.equal(deadline.value,'2026-10-26');assert.equal(deadline.dataset.userSelected,'true');
 deadline.value='2026-10-22';deadline.dataset.userSelected='true';deadline.dataset.autoDetected='true';ctx.deadlinePreviewPrefill=true;document.getElementById('w-deadline-confirm').checked=true;
 ctx.resetDeadlineForSourceChange();
 assert.equal(deadline.value,'');assert.equal(deadline.dataset.userSelected,undefined);assert.equal(deadline.dataset.autoDetected,undefined);
 assert.equal(ctx.deadlinePreviewPrefill,false);assert.equal(document.getElementById('w-deadline-confirm').checked,false);
 ctx.resetDetectedDetails();
 assert.equal(type.value,'business');assert.equal(document.getElementById('w-subject').value,'general');
 assert.equal(document.getElementById('w-currency').value,'');assert.equal(document.getElementById('w-currency-other').value,'');
 const currency=document.getElementById('w-currency');currency.value='EUR';currency.dataset.userSelected='true';
 ctx.analyzeGrant(true);await flush();assert.equal(currency.value,'EUR');assert.equal(document.getElementById('w-currency-detected').hidden,true);
 response.quick_preview.suggestion_method='unaccepted';response.quick_preview.subject='healthcare';ctx.analyzeGrant(true);await flush();
 assert.equal(document.getElementById('w-subject').value,'general');
 response={status:'blocked',extraction_id:'id-1',extraction_token:'secret'};
 ctx.analyzeGrant(true,true); await flush(); assert.equal(ctx.analysisOk,false);
 response={status:'ready',title:'Missing capabilities'};
 ctx.analyzeGrant(true); await flush(); assert.equal(ctx.analysisOk,false);
 response={ok:true,title:'Legacy response without verified documents'};
 ctx.analyzeGrant(true); await flush(); assert.equal(ctx.analysisOk,false);
 input='http://a.co';response={status:'processing',awaiting_payment:true,extraction_id:'short-url',extraction_token:'token',quick_preview:{status:'unavailable'}};
 ctx.analyzeGrant(true);await flush();assert.equal(requests.at(-1).input,input);assert.equal(ctx.analysisOk,true);
 let resolveOld;
 ctx.fetch=()=>new Promise(resolve=>{resolveOld=resolve;});
 // Switching to paste is deliberate, retains the link and invalidates in-flight results.
 vm.runInContext(html.slice(html.indexOf('var debounceT ='),html.indexOf('function proposalCurrency()')),ctx);
 const sourceInput=input;
 document.getElementById('w-grant').value=input;
 ctx.showOpportunityResult({status:'processing',awaiting_payment:true,quick_preview:{status:'unavailable',failure_reason:'login_required'}});
 const fallbackCard=document.getElementById('gpreview');
 assert.match(content(fallbackCard),/This page needs a login or verification/);
 const fallbackActions=fallbackCard.children.find(n=>n.style.display==='flex');
 assert.equal(fallbackActions.style.gap,'16px');assert.equal(fallbackActions.style.flexWrap,'wrap');
 assert.equal(fallbackActions.children[0].className,'text-link');
 const pasteAction=fallbackActions.children.find(n=>n.textContent==='Paste full page text');
 assert.equal(input,sourceInput);
 ctx.analyzeGrant(true);
 ctx.analyzedDeadline='2026-10-27';document.getElementById('w-deadline').value='2026-10-27';
 document.getElementById('w-deadline').dataset.userSelected='true';
 pasteAction.events.click();
 assert.equal(input,'');assert.equal(document.getElementById('w-grant').focused,true);
 assert.equal(ctx.analysisOk,false);assert.equal(ctx.opportunityExtractionId,'');assert.equal(ctx.opportunityExtractionToken,'');
 assert.equal(ctx.analyzedDeadline,'');assert.equal(document.getElementById('w-deadline').value,'');
 assert.equal(document.getElementById('opportunity-paste-source').hidden,false);
 assert.match(content(document.getElementById('opportunity-paste-source')),/Copy the full page text/);
 assert.equal(document.getElementById('opportunity-paste-source').children[1].href,new URL(sourceInput).href);
 assert.equal(document.getElementById('opportunity-paste-source').children[1].rel,'noopener noreferrer');
 resolveOld({json:async()=>({status:'processing',awaiting_payment:true,extraction_id:'old',extraction_token:'old-token',quick_preview:{status:'preview',suggestion_method:'jev_source_selection',display_title:'Stale title',subject:'education'}})}); await flush();
 assert.equal(ctx.analysisOk,false); assert.equal(ctx.opportunityExtractionId,'');assert.equal(ctx.opportunityDetails,null);
 assert.equal(document.getElementById('w-subject').value,'general');
 input='Complete supplied opportunity requirements. '.repeat(30);document.getElementById('w-grant').value=input;
 document.getElementById('w-grant').dispatchEvent(new ctx.Event('input'));
 response={status:'processing',awaiting_payment:true,extraction_id:'pasted-id',extraction_token:'pasted-token',quick_preview:{status:'preview'}};
 ctx.fetch=async(url,options)=>{requests.push(JSON.parse(options.body));return {json:async()=>response};};
 ctx.analyzeGrant(true);await flush();
 assert.equal(requests.at(-1).input,input);assert.equal(ctx.canContinueIntake(),true);
 assert.equal(document.getElementById('opportunity-paste-source').hidden,false);
 input='https://example.org/different-tender';document.getElementById('w-grant').value=input;document.getElementById('w-grant').dispatchEvent(new ctx.Event('input'));
 assert.equal(document.getElementById('opportunity-paste-source').hidden,true);
 vm.runInContext(html.slice(html.indexOf('function renderSuff(j)'), html.indexOf('// Payment happens ONLY')),Object.assign(ctx,{esch:s=>String(s).replace(/</g,'&lt;')}));
 ctx.renderSuff({message:'Source expired <script>',reason:'opportunity_analysis_required'});
 assert.match(document.getElementById('suff-result').innerHTML,/Source expired &lt;script>/);
 assert.match(html,/clearTimeout\(analysisPoll\); analysisSequence\+\+/);
 assert.match(html,/Number\(steps\[i\]\.dataset\.step\) === this.step/);
 assert.match(html,/data-step="0">\s*<h3>Start with the opportunity/);
 assert.match(html,/if \(!analysisOk \|\| lastAnalyzed !== this.val\('w-grant'\)\)/);
 // Background navigation cannot cross payment even with a stale clearance token.
 const payStart=html.indexOf('  pay: function () {'),payEnd=html.indexOf('\n};\n\n// openers',payStart);
 vm.runInContext('var checkoutGate = {'+html.slice(payStart,payEnd)+'\n};',ctx);
 let sourceReviews=0,validations=0;
 ctx.analyzeGrant=()=>{sourceReviews++;};ctx.fetch=()=>{throw Error('Checkout must not send intake while source review is pending');};
 const checkout={step:6,pendingToken:'stale',val:()=>input,render(){},validate(){validations++;}};
 ctx.analysisOk=false;ctx.analysisBackground=true;ctx.analyzing=true;ctx.checkoutGate.pay.call(checkout);
 assert.equal(checkout.step,0);assert.equal(sourceReviews,1);
 ctx.analysisOk=true;ctx.lastAnalyzed=input;ctx.deadlineRequiresManual=true;ctx.cb=()=>false;
 let payments=0;ctx.goToPayment=()=>{payments++;};ctx.checkoutGate.pay.call(checkout);assert.equal(validations,0);assert.equal(payments,1);

 console.log('Opportunity UI checks passed: ready gate, polling capabilities, safe links, no inferred currency, ordered steps.');
})().catch(e=>{console.error(e);process.exitCode=1;});
